//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Infrastructure.Repositories.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class pProduct
    {
        public int ProductId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Abstract { get; set; }
        public string Content { get; set; }
        public string Thumbnail { get; set; }
    }
}
